#!/bin/bash

url=$1

echo "Starting archiving!"

youtube-dl $url \
--download-archive downloaded.txt \
-o "%(uploader)s/%(upload_date)s - %(title)s/%(uploader)s - %(title)s - %(upload_date)s %(id)s.%(ext)s" \
-f best \
--write-thumbnail \
--write-description \
--write-info-json \
--write-annotations \
--all-subs

echo "Archiving done!"
